# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc ""
  homepage "https://katallaxie.github.io/g/"
  version "0.0.1-alpha.3"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.3/g_0.0.1-alpha.3_darwin_arm64.tar.gz"
      sha256 "8c4928e9a7513e57cb3adbe49ef7c7152f22d0df2a21cbf440c229e1242e4e9e"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.3/g_0.0.1-alpha.3_darwin_amd64.tar.gz"
      sha256 "c3986e30cee932ddac2ccdb135088810311e4feb6f38d7c78a1d91e877a377b8"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.3/g_0.0.1-alpha.3_linux_arm64.tar.gz"
      sha256 "b37816b79065fa004b11b6cb49d57eb70ea8621edc65ebc92d9492326f9652b4"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.3/g_0.0.1-alpha.3_linux_amd64.tar.gz"
      sha256 "01a0b9bc9581e3eafceb960109728c9d811acc94ba282e33efb5a7a3c7e008a5"

      def install
        bin.install "g"
      end
    end
  end
end
