# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc ""
  homepage "https://katallaxie.github.io/g/"
  version "0.0.1-alpha.2"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.2/g_0.0.1-alpha.2_darwin_amd64.tar.gz"
      sha256 "76ef03af0d5085b4c75ea29535a5a4ae0785af7a28168a67273a9ef2d9e839ee"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.2/g_0.0.1-alpha.2_darwin_arm64.tar.gz"
      sha256 "e9b0071c7efe30a8f0fa4f058c27e862462dd1d22101afebfe72bcc9b034f928"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.2/g_0.0.1-alpha.2_linux_amd64.tar.gz"
      sha256 "6e12e8ad946d9e03621ea7fba6f90ebdd763c428b1df72a441c034cb2dc41b44"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.2/g_0.0.1-alpha.2_linux_arm64.tar.gz"
      sha256 "6915e1c10734ca2bd0957bd0e5228ddb4de5024b7167b8b2c3541c3677c0cf35"

      def install
        bin.install "g"
      end
    end
  end
end
