# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc ""
  homepage "https://katallaxie.github.io/g/"
  version "0.0.1-alpha.4"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.4/g_0.0.1-alpha.4_darwin_arm64.tar.gz"
      sha256 "ef3dd5ad39c52dd2366c58cfe02095c1393c3ddfc1bb79d84fe2ddd6990bf990"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.4/g_0.0.1-alpha.4_darwin_amd64.tar.gz"
      sha256 "e4a955b21fbd70c8fda9c4c3a998de041099acb2d12770558375bcb29e04552a"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.4/g_0.0.1-alpha.4_linux_amd64.tar.gz"
      sha256 "2e8b9b61e68288668d236f68412405d6646b43bfd0dbef549d1bd795ac515b98"

      def install
        bin.install "g"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/g/releases/download/v0.0.1-alpha.4/g_0.0.1-alpha.4_linux_arm64.tar.gz"
      sha256 "42270977550839ca3d580ac14ed169ceae4c6580bc63418154e919a46d29bafd"

      def install
        bin.install "g"
      end
    end
  end
end
